apiVersion: kueue.x-k8s.io/v1alpha2
kind: ClusterQueue
metadata:
  name: team-b-cq
spec:
  cohort: all # team-a-cq and team-b-cq share the same cohort
  namespaceSelector: {}
  resources:
  - name: "cpu"
    flavors:
    - name: on-demand
      quota:
        max: 15
        min: 10
    - name: spot # The spot resource is not used for now
      quota:
        min: 0
  - name: "memory"
    flavors:
    - name: default
      quota:
        min: 36Gi
---
apiVersion: kueue.x-k8s.io/v1alpha2
kind: LocalQueue
metadata:
  namespace: team-b
  name: team-b-lq
spec:
  clusterQueue: team-b-cq