apiVersion: kueue.x-k8s.io/v1alpha2
kind: ClusterQueue
metadata:
  name: cq
spec:
  namespaceSelector: {}
  queueingStrategy: BestEffortFIFO # Default queueing strategy
  resources:
  - name: "cpu"
    flavors:
    - name: on-demand
      quota:
        min: 10
  - name: "memory"
    flavors:
    - name: default
      quota:
        min: 10Gi
  - name: "nvidia.com/gpu"
    flavors:
    - name: render
      quota:
        min: 10
  - name: "ephemeral-storage"
    flavors:
    - name: storage
      quota:
        min: 5Gi