apiVersion: kueue.x-k8s.io/v1alpha2
kind: LocalQueue
metadata:
  namespace: team-a # LocalQueue under team-a namespace
  name: team-a-lq
spec:
  clusterQueue: cq # Point to the ClusterQueue cq
---
apiVersion: kueue.x-k8s.io/v1alpha2
kind: LocalQueue
metadata:
  namespace: team-b # LocalQueue under team-b namespace
  name: team-b-lq
spec:
  clusterQueue: cq # Point to the ClusterQueue cq